apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  namespace: eshop-staging
  name: storage.googleapis.com
  annotations:
     cnrm.cloud.google.com/disable-dependent-services: "true"
